apiVersion: v1 
kind: Service 
metadata: 
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app 
spec:
  ports: # No nodeport since it will be a internal service
    - port: 6379
      targetPort: 6379
  selector: # Link this service to the 
    name: redis-pod
    app: demo-voting-app # part of the same app as voting app
    
      
