apiVersion: v1 
kind: Service 
metadata: 
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app 
spec:
  type: NodePort # Option:- LoadBalancer when deploying on cloud
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector: # Link this service to the 
    name: result-app-pod 
    app: demo-voting-app # part of the same app as voting app