apiVersion: apps/v1
kind: Deployment
#Specifying the name of the deployment
metadata:
  name: voting-app-deploy
  labels:
    name: voting-app-deploy 
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-app-pod 
      app: demo-voting-app
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod 
        app: demo-voting-app
    spec:
      containers:
        - name: voting-app # Name of the container
          image: kodekloud/examplevotingapp_vote:v1 # the docker image file(docker hub or local image)
          ports:
            - containerPort: 80 # port on which the application will be running