apiVersion: v1 
kind: Service 
metadata: 
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app 
spec:
  type: NodePort   # Option:- LoadBalancer when deploying on cloud
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector: # Link this service to the 
    name: voting-app-pod 
    app: demo-voting-app # part of the same app as voting app
    
      
